"""
Prompts module for the CV-maker application.
"""

from .system_prompts import (
    SYSTEM_PROMPT_GENERAL,
    SYSTEM_PROMPT_CV,
    SYSTEM_PROMPT_LETTRE,
    SYSTEM_PROMPT_ENTRETIEN,
    SYSTEM_PROMPT_ANALYSE,
    SYSTEM_PROMPT_COACH,
    SYSTEM_PROMPT_LINKEDIN
)

from .task_prompts import (
    PROMPT_ANALYSE_OFFRE,
    PROMPT_OPTIMISER_CV,
    PROMPT_LETTRE_MOTIVATION,
    PROMPT_PREPARATION_ENTRETIEN,
    PROMPT_ANALYSE_COMPATIBILITE,
    PROMPT_COACH_CONVERSATION,
    PROMPT_LINKEDIN_POST,
    PROMPT_ADAPTER_CV_TEMPLATE,
    PROMPT_MODIFIER_CV_COMPLET
)

__all__ = [
    'SYSTEM_PROMPT_GENERAL',
    'SYSTEM_PROMPT_CV',
    'SYSTEM_PROMPT_LETTRE',
    'SYSTEM_PROMPT_ENTRETIEN',
    'SYSTEM_PROMPT_ANALYSE',
    'SYSTEM_PROMPT_COACH',
    'PROMPT_ANALYSE_OFFRE',
    'PROMPT_OPTIMISER_CV',
    'PROMPT_LETTRE_MOTIVATION',
    'PROMPT_PREPARATION_ENTRETIEN',
    'PROMPT_ANALYSE_COMPATIBILITE',
    'PROMPT_COACH_CONVERSATION'
]
